import { useMemo } from "react";
import type { FamilyDataState } from "./familyDataTypes";

/**
 * Memoise the provider's context value. The object is rebuilt only when one
 * of its fields changes identity, so consumers re-render exactly as often as
 * the fields they read.
 */
export function useFamilyDataValue(fields: FamilyDataState): FamilyDataState {
  const {
    familyId,
    userId,
    apiClient,
    members,
    ownerId,
    membersState,
    membersError,
    familyEndpoint,
    bookshelfMembers,
    bookshelfState,
    bookshelfError,
    borrowRequests,
    borrowRequestsState,
    borrowRequestsError,
    refreshBorrowRequests,
    applyBorrowStatus,
    refreshMembers,
    refreshBookshelf,
    updateMemberDisplayName,
    updateMember,
    updatedBookIds,
    hasBookshelfUpdates,
    markBookshelfSeen,
    hiddenRefs,
    isHidden,
    toggleHidden,
    favoriteRefs,
    isFavorite,
    toggleFavorite,
    prefsSyncFailed,
  } = fields;

  return useMemo<FamilyDataState>(
    () => ({
      familyId,
      userId,
      apiClient,
      members,
      ownerId,
      membersState,
      membersError,
      familyEndpoint,
      bookshelfMembers,
      bookshelfState,
      bookshelfError,
      borrowRequests,
      borrowRequestsState,
      borrowRequestsError,
      refreshBorrowRequests,
      applyBorrowStatus,
      refreshMembers,
      refreshBookshelf,
      updateMemberDisplayName,
      updateMember,
      updatedBookIds,
      hasBookshelfUpdates,
      markBookshelfSeen,
      hiddenRefs,
      isHidden,
      toggleHidden,
      favoriteRefs,
      isFavorite,
      toggleFavorite,
      prefsSyncFailed,
    }),
    [
      familyId,
      userId,
      apiClient,
      members,
      ownerId,
      membersState,
      membersError,
      familyEndpoint,
      bookshelfMembers,
      bookshelfState,
      bookshelfError,
      borrowRequests,
      borrowRequestsState,
      borrowRequestsError,
      refreshBorrowRequests,
      applyBorrowStatus,
      refreshMembers,
      refreshBookshelf,
      updateMemberDisplayName,
      updateMember,
      updatedBookIds,
      hasBookshelfUpdates,
      markBookshelfSeen,
      hiddenRefs,
      isHidden,
      toggleHidden,
      favoriteRefs,
      isFavorite,
      toggleFavorite,
      prefsSyncFailed,
    ],
  );
}
